[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
[build]
  command = "npm run build"
  publish = "dist"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
